test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})


my_data <- tibble::tribble(
  ~x, ~y, ~z, ~n,
  2,4,3,3,
  2,4,3,4,
  2,4,3,5,
  2,4,3,6,
  2,4,3,7,
  2,4,3,8,
  2,4,3,9,
  2,4,3,10,
  2,4,3,12)

# Plots the output values generated by the data frame supplied by the user
calcn2(my_data)
